export const URL_HOME_PAGE = "/"
export const URL_LOG_IN_PAGE = "/log-in"
export const URL_REGISTER_PAGE = "/register"
export const URL_SEARCH_PAGE = "/search"
export const URL_ADD_PRODUCT_PAGE = "/add-product"
