export const URL_HOME_PAGE = "/"
export const URL_LOG_IN_PAGE = "/log-in"
export const URL_REGISTER_PAGE = "/register"
export const URL_SEARCH_PAGE = "/search"
export const URL_ADD_PRODUCT_PAGE = "/add-product"
export const URL_EDIT_PRODUCT_PAGE = "/edit-product/:productID"
export const URL_USER_PRODUCTS_PAGE = "/user-products"
export const URL_CART_PAGE = "/cart"
